import Head from "next/head";
import styles from "./index.module.css";

export default function Home() {
  console.log("home page rendered");
  return (
    <>
      <Head>
        <title>WordNerd Beta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/WordNerd Logo Transparent.png" />
      </Head>
      <main className={styles.main}>
        <div>Home Page</div>
      </main>
    </>
  );
}
