import Head from "next/head";
import styles from "./index.module.css";
import { Paper } from "@mui/material";
import { createTheme, ThemeProvider } from "@mui/material/styles";

import CircleIcon from "@mui/icons-material/Circle";
import AOS from "aos";
import "aos/dist/aos.css";
import { useEffect } from "react";
import HeroContainer from "../components/homepage/HeroContainer.js";

export default function Home() {
  useEffect(() => {
    AOS.init({ duration: 500 });
  }, []);
  return (
    <>
      <Head>
        <title>WordNerd Beta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/wn_logo_transparent.png" />
      </Head>

      <div className={styles.main}>
        <HeroContainer>
          <div data-aos="fade-in">
            <h2>A thesaurus</h2>
          </div>
        </HeroContainer>
        <HeroContainer>
          <h2 data-aos="fade-in">for words</h2>
          <div style={{ zIndex: 3 }} data-aos="fade-in">
            <div className={styles.action_text}>
              <CircleIcon />
              <p>user created: </p>
            </div>
            <div className={styles.card}>
              <Paper className={styles.paper}></Paper>
            </div>
          </div>
        </HeroContainer>
        <HeroContainer>
          <h2 data-aos="fade-in">idioms</h2>
          <div data-aos="fade-in" style={{ zIndex: 2 }}>
            <div className={styles.action_text}>
              <CircleIcon />
              <p>user thinks this is related to: </p>
            </div>
            <div className={styles.card}>
              <Paper className={styles.paper}></Paper>
            </div>
            <div className={styles.line}></div>
          </div>
        </HeroContainer>
        <HeroContainer>
          <h2 data-aos="fade-in">proverbs</h2>
          <div data-aos="fade-in" style={{ zIndex: 1 }}>
            <div className={styles.action_text}>
              <CircleIcon />
              <p>user thinks this is related to: </p>
            </div>
            <div className={styles.card}>
              <Paper className={styles.paper}></Paper>
            </div>
            <div className={styles.line}></div>
          </div>
        </HeroContainer>
        <HeroContainer>
          <h2 data-aos="fade-in">and quotes</h2>
          <div data-aos="fade-in">
            <div className={styles.action_text}>
              <CircleIcon />
              <p>user thinks this is related to: </p>
            </div>
            <div className={styles.card}>
              <Paper className={styles.paper}></Paper>
            </div>
            <div className={styles.line}></div>
          </div>
        </HeroContainer>
      </div>
    </>
  );
}
