import Head from "next/head";
import styles from "./index.module.css";
import Searchbar from "../components/Searchbar.js";

export default function Home() {
  return (
    <>
      <Head>
        <title>WordNerd Beta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>some search result here</div>
      </main>
    </>
  );
}
